Repository UIUC-PPL/projections, pull requests merged in 2021-06, with the labels that each got.

#121 Fix Timeline boundary rendering
  src/projections/Tools/Timeline/EntryMethodObject.java
  src/projections/Tools/Timeline/MainPanel.java
Labels: bug, enhancement

#122 bin/projections: check for projections.jar
  bin/projections
Labels: bin/projections

#123 CI on MacOS
  .github/workflows/test.yml
Labels: CI
